### ISSUE TITLE
Hunting Horn Shockwave calculation incorrect

### ISSUE THREAD

**Issue by FastiJan** [dsankar1/mhwcalculator-ui#2]
2 Issues to correct:
 - Shockwave ignores current sharpness. Always uses 100% sharpness.
 - Shockwave ignores affinity(positive and negative) hits. Always uses 0% affinity.

Workaround:
 - Manually set "net affinity" to 0%
 - Manually set sharpness to green to get elemental damage part (under true element).
 - Manually set sharpness to yellow and "Hide element" to get raw damage part (under the Shockwave, not the "true damage").
 - Sum up the damage parts for true Shockwave damage.

Background info: https://www.reddit.com/r/MonsterHunter/comments/7wnmaq/hunting_horn_and_you_understanding_the_shockwave/

**Comment by dsankar1** [comment]
Apologies on how late this fix is, but sharpness and affinity no longer factor into Shockwave damage
