### ISSUE TITLE
Iceborne Purple sharpness

### ISSUE THREAD

**Issue by Xigmah** [dsankar1/mhwcalculator-ui#3]
Hey dsanker!

Thank you again for this amazing app! I wanted to message you directly but couldn't find a way to do so. I'm excited to use this!
However I noticed that your app isn't up-to-date with the new numbers! I'd love to help on this or just pass on what I've done, 'cause I'd love to get some calculations for that sweet sweet purple sharpness!

I've attached some changes to add the sharpness in, I tried creating an iceborne branch but (completely understandably) I don't have permission to push the branch. Either way, thanks for everything you've done!

Regards,
Xigmah

[Purple Sharpness (Just files).zip](https://github.com/dsankar1/mhwcalculator-ui/files/3618952/Purple.Sharpness.Just.files.zip)
[Purple Sharpness.zip](https://github.com/dsankar1/mhwcalculator-ui/files/3618953/Purple.Sharpness.zip)

**Comment by dsankar1** [comment]
Hey! Sorry for the late response, but I'm glad you find the app useful! I'll take a look at the resources attached, and push those sharpness changes ASAP!

**Comment by Xigmah** [comment]
Oh! Hello!

No worries at all, I figured it was a long shot!
My edits are a little old and incorrect, with purple sharpness having a
different mod (it's an additional 5% physical and 10% elemental), but I'd
be happy to take a look and tweak it back!
I haven't built the app with the changes, I personally don't know much JS
(more of a C++ or Python guy myself!) but thought I'd take a crack at it!
So if your compile/build fails, let me know and I'll try to find a way
around any errors!

Regards,
Xigmah

**Comment by dsankar1** [comment]
The calculator now supports purple sharpness! If you ever want to contribute feel free to create a pull request :) thanks
