### ISSUE TITLE
Iceborne purple sharpness + new augments

### ISSUE THREAD

**Issue by DubskiDude** [dsankar1/mhwcalculator-ui#4]
Hey there, been using your calculator for forever - it's been a very important resource. There was a previous issue posted here about purple sharpness (which this calculator sorely needs), but there's also the new augmenting system.

To boil it all down, attack augments now have four levels (+5 true raw each), affinity augments have four levels each (+10% for the first, +5% for the rest), and the new element augments (four levels total, +3 true element damage each).

I've searched and searched for an updated Iceborne damage calculator, but there doesn't seem to be one, so yours is primed and ready to be the single best resource for people playing the expansion. I'm really hoping for an updated version of this calculator! Regardless, thanks for making it.

**Comment by dsankar1** [comment]
My pleasure! Makes me very happy to hear that the calculator is useful to you. I've added a 4th level to the existing attack/affinity augments, and included the elemental boost augment.
